name: flutter_new_app
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Recommended lint rules for Flutter projects
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For splash screen and launcher icons
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

# Flutter Launcher Icons Configuration
flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/logo.png"
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo.png" 
  android: false
  ios: true
flutter:
  uses-material-design: true

  # Image assets
  assets:
    - assets/images/
    # Example: - assets/images/logo.png

  # To add custom fonts (optional)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
